CREATE DATABASE `tcp-server`;

USE `tcp-server`;

CREATE TABLE IF NOT EXISTS received_data (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);